### PR TITLE
(test) Unit Tests for ChaosEngine Experiment List ConfigMap and Secret Validation

### PR DESCRIPTION
**Pull request by christopherfriedrich**
**What this PR does / why we need it**:

Unit tests for `ValidateChaosExperimentsConfigMaps` and `ValidateChaosExperimentsSecrets`

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:

**Checklist:**
- [ ] Fixes #<issue number>
- [ ] Labelled this PR & related issue with `documentation` tag
- [ ] PR messages has document related information
- [ ] Labelled this PR & related issue with `breaking-changes` tag
- [ ] PR messages has breaking changes related information
- [ ] Labelled this PR & related issue with `requires-upgrade` tag
- [ ] PR messages has upgrade related information
- [ ] Commit has unit tests
- [ ] Commit has integration tests

### CODE REVIEW

**Comment by rahulchheda** [comment]
Great PR @christopherfriedrich, thanks for initializing the tests in this repo. Could you just do me one more favor and add the coverage for the code. We can create a issue out of it, and then proceed package by package increasing the code coverage.
Btw, you might have to do a `go mod vendor` to get the `fake` package into the vendor dir.

**Review by rahulchheda — APPROVED** [review]
/lgtm 
Will merge this in a while.

**Comment by rahulchheda** [comment]
Just a little suspicious about no changes in `go.mod` and `go.sum` but a lot of changes in `/vendor`
cc: @christopherfriedrich

**Comment by christopherfriedrich** [comment]
I am too @rahulchheda, i did a `go mod tidy` after adding the kubernetes `fake` dependecy via `go get`.

**Review by ksatchit — APPROVED** [review]

**Pull request merged**
